protected/controllers/SiteController.php
<?php

class SiteController extends Controller
{
    public $meta_desc = '';
    public $meta_keywords = '';
	/**
	 * Declares class-based actions.
	 */
	public function actions()
	{
		return array(
			// captcha action renders the CAPTCHA image displayed on the contact page
			'captcha'=>array(
				'class'=>'CCaptchaAction',
				'backColor'=>0xFFFFFF,
			),
			// page action renders "static" pages stored under 'protected/views/site/pages'
			// They can be accessed via: index.php?r=site/page&view=FileName
			'page'=>array(
				'class'=>'CViewAction',
			),
		);
	}

	/**
	 * This is the default 'index' action that is invoked
	 * when an action is not explicitly requested by users.
	 */
	public function actionIndex()
	{
	    $this->layout='column1';
	    
	    // get the list of latest locations
	    $temp = Yii::app()->db->createCommand();
		$temp->select('*');
        $temp->from('store');
        $temp->order(array('id DESC'));
        $temp->limit(6);
        $stores = $temp->queryAll();
        
		// renders the view file 'protected/views/site/index.php'
		// using the default layout 'protected/views/layouts/main.php'
		$this->render('index', array('store_list'=>$stores));
	}
	
	public function actionAbout_us()
	{
	    $this->pageTitle = 'Canadian Passport Photos | About Us';
	    $this->meta_desc = "Canadian passport photos - About our passport photo service";
	    $this->meta_keywords = 'About, passports, immigration, id, prints, coupons, deals, guarenteed';
	    $this->render('about_us');
	}
	
	public function actionResources()
	{
	    $this->pageTitle = 'Canadian Passport Photos | Resources';
	    $this->meta_desc = "Canadian passport photos - Resources and helpful tips for Passport, ID, Immigration, Government and International Document Photographs.";
	    $this->meta_keywords = 'passport resources, photography, photo, passport, immigration, id, passport photos, ';
	    $this->render('resources');
	}
	
	public function actionOnthego()
	{
	    $this->pageTitle = 'Canadian Passport Photos | Photos on-the-go';
	    $this->meta_desc = "Canadian passport photos - After hours and emergency passport photo service";
	    $this->meta_keywords = 'mobile, passport photos, emergency, at home, on location photos, urgent photos, emergency travel ID, 24 hour passport photo, 24 hours ';
	    $this->render('onthego');
	}
	
	public function actionStore_locator()
	{
	    $this->pageTitle = 'Canadian Passport Photos | Photos on-the-go';
	    $this->meta_desc = "Canadian passport photos - After hours and emergency passport photo service";
	    $this->meta_keywords = 'mobile, passport photos, emergency, at home, on location photos, urgent photos, emergency travel ID, 24 hour passport photo, 24 hours ';
	    $this->render('store_locator');
	}

	/**
	 * This is the action to handle external exceptions.
	 */
	public function actionError()
	{
		if($error=Yii::app()->errorHandler->error)
		{
			if(Yii::app()->request->isAjaxRequest)
				echo $error['message'];
			else
				$this->render('error', $error);
		}
	}

	/**
	 * Displays the contact page
	 */
	public function actionContact()
	{
		$model=new ContactForm;
		if(isset($_POST['ContactForm']))
		{
			$model->attributes=$_POST['ContactForm'];
			if($model->validate())
			{
				$name='=?UTF-8?B?'.base64_encode($model->name).'?=';
				$subject='=?UTF-8?B?'.base64_encode($model->subject).'?=';
				$headers="From: $name <{$model->email}>\r\n".
					"Reply-To: {$model->email}\r\n".
					"MIME-Version: 1.0\r\n".
					"Content-type: text/plain; charset=UTF-8";

				mail(Yii::app()->params['adminEmail'],$subject,$model->body,$headers);
				Yii::app()->user->setFlash('contact','Thank you for contacting us. We will respond to you as soon as possible.');
				$this->refresh();
			}
		}
		$this->render('contact',array('model'=>$model));
	}

	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model=new LoginForm;

		// if it is ajax validation request
		if(isset($_POST['ajax']) && $_POST['ajax']==='login-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if(isset($_POST['LoginForm']))
		{
			$model->attributes=$_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if($model->validate() && $model->login())
				$this->redirect(Yii::app()->user->returnUrl);
		}
		// display the login form
		$this->render('login',array('model'=>$model));
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
}

protected/controllers/StoreController.php
<?php

class StoreController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/column2';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','view','locator'),
				'users'=>array('*'),
			),
			array('allow', // allow authenticated user to perform 'create' and 'update' actions
				'actions'=>array('create','update'),
				'users'=>array('@'),
			),
			array('allow', // allow admin user to perform 'admin' and 'delete' actions
				'actions'=>array('admin','delete'),
				'users'=>array('admin'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$this->render('view',array(
			'model'=>$this->loadModel($id),
		));
	}

	/**
	 * Creates a new model.
	 * If creation is successful, the browser will be redirected to the 'view' page.
	 */
	public function actionCreate()
	{
		$model=new Store;

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Store']))
		{
			$model->attributes=$_POST['Store'];
			$address = (isset($_POST['Store']['postal_code']) && $_POST['Store']['postal_code'] != '') ? $_POST['Store']['postal_code'] : $_POST['Store']['address'].','.$_POST['Store']['city'].','.$_POST['Store']['province'];
			
			$location = $this->get_location($address);
			
			if ($location)
			{
			    $model->lat = $location['lat'];
			    $model->lng = $location['long'];
			    if($model->save())
			        $this->redirect(array('view','id'=>$model->id));
			}

		}

		$this->render('create',array(
			'model'=>$model,
		));
	}
	
	function get_location($address)
	{
	    // get lat and long of the location
		$post = 'http://maps.googleapis.com/maps/api/geocode/json?address='.(str_ireplace(' ','+',$address)).'&sensor=false';
		//var_dump($post);
		$data = CJSON::decode(file_get_contents($post), true);
		//var_dump($data);
		if ($data['results'][0]['geometry']['location']['lat'] != 0 && $data['results'][0]['geometry']['location']['lng'] !=0)
		{
		    return array('lat'=>$data['results'][0]['geometry']['location']['lat'], 'long'=>$data['results'][0]['geometry']['location']['lng']);
		}
		else
		return null;
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate($id)
	{
		$model=$this->loadModel($id);

		// Uncomment the following line if AJAX validation is needed
		// $this->performAjaxValidation($model);

		if(isset($_POST['Store']))
		{
			$model->attributes=$_POST['Store'];
			// get lat and long of the location
			$address = (isset($_POST['Store']['postal_code']) && $_POST['Store']['postal_code'] != '') ? $_POST['Store']['postal_code'] : $_POST['Store']['address'].','.$_POST['Store']['city'].','.$_POST['Store']['province'];
			
			$location = $this->get_location($address);
			
			if ($location)
			{
			    $model->lat = $location['lat'];
			    $model->lng = $location['long'];
			    if($model->save())
			        $this->redirect(array('view','id'=>$model->id));
			}
		}

		$this->render('update',array(
			'model'=>$model,
		));
	}

	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id)
	{
		$this->loadModel($id)->delete();

		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('admin'));
	}

	/**
	 * Lists all models.
	 */
	public function actionIndex()
	{
		$dataProvider=new CActiveDataProvider('Store', array());
		$this->render('index',array(
			'dataProvider'=>$dataProvider,
		));
	}
	
	public function actionLocator()
	{
	    if (isset($_POST['filter']))
	    {

	        $dia = 6371;//($_POST['units'] == 'm') ? 3959 : 6371;
	        $distance = $_POST['radius'];

	        $post = 'http://maps.googleapis.com/maps/api/geocode/json?address='.(str_ireplace(' ','+',$_POST['address'])).'&sensor=false';
			$data = CJSON::decode(file_get_contents($post), true);
			$lat = $data['results'][0]['geometry']['location']['lat'];
			$lng = $data['results'][0]['geometry']['location']['lng'];

			$temp = Yii::app()->db->createCommand();
			$temp->select('id, lat, lng, name, address, phone_number,city, ( '.$dia.' * acos( cos( radians('.$lat.') ) * cos( radians( lat ) ) * cos( radians( lng ) - radians('.$lng.') ) + sin( radians('.$lat.') ) * sin( radians( lat ) ) ) ) AS distance');
        	$temp->from('store');
        	$temp->having('distance < '.$distance);
        	$temp->order(array('distance ASC'));
        	$temp->limit(20);
        	$stores = $temp->queryAll();
	        //var_dump($stores);
	    }
	    elseif ($_POST['all'])
	    {
	        $temp = Yii::app()->db->createCommand('SELECT `id`, `lat`, `lng`, `name`, `address`, `phone_number`, `city`, "0" AS `distance`
FROM `store`
ORDER BY `city` ASC');
	        //$temp->select('id, lat, lng, name, address, phone_number,city, "0" as distance');
	        //$temp->from('store');
        	//$temp->having('distance < '.$distance);
        	//$temp->order(array('city ASC'));
        	//$temp->limit(20);
        	$stores = $temp->queryAll();
	    }
		
		$this->render('locator',array(
			'dataProvider'=>$stores,
		));
	}

	/**
	 * Manages all models.
	 */
	public function actionAdmin()
	{
		$model=new Store('search');
		$model->unsetAttributes();  // clear any default values
		if(isset($_GET['Store']))
			$model->attributes=$_GET['Store'];

		$this->render('admin',array(
			'model'=>$model,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Store the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Store::model()->findByPk($id);
		if($model===null)
			throw new CHttpException(404,'The requested page does not exist.');
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param Store $model the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if(isset($_POST['ajax']) && $_POST['ajax']==='store-form')
		{
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}
}

protected/views/layouts/column1.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div id="content">
	<?php echo $content; ?>
</div><!-- content -->
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php /* @var $this Controller */ ?>
<?php $this->beginContent('//layouts/main'); ?>
<div class="span-19">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<div class="span-5 last">
	<div id="sidebar">
	<?php
		$this->beginWidget('zii.widgets.CPortlet', array(
			'title'=>'Operations',
		));
		$this->widget('zii.widgets.CMenu', array(
			'items'=>$this->menu,
			'htmlOptions'=>array('class'=>'operations'),
		));
		$this->endWidget();
	?>
	</div><!-- sidebar -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<?php /* @var $this Controller */ ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />
	<META Name="description" CONTENT="<?php echo (isset($this->meta_desc) ? CHtml::encode($this->meta_desc) : ''); ?>">

	<!-- blueprint CSS framework -->
	<!-- <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" /> -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<!-- <link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" /> -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen_style.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body class="gridLayout">

<div class="container" id="container">
<div class="contentWrapper">
	<div id="header"> 
    <div class="logo"><h1><a href="#">CanadianPassportPhotos.ca</a></h1></div>
    <div class="headerMenu">
    <ul>
        <li><a href="index.html">Home</a></li>
        <li><a href="site_contact.html">Contact us</a></li>
    </ul>
    <!-- end headerMenu --></div>
  <!-- end #header --></div>

	<div id="globalNavigation">
		<?php 
		$this->widget('zii.widgets.CMenu',array(
			'items'=>array(
				array('label'=>'About us', 'url'=>array('/site/about_us')),
				array('label'=>'Locations', 'url'=>array('/store/locator')),
				array('label'=>'Resources', 'url'=>array('/site/resources')),
				array('label'=>'Photos on-the-go', 'url'=>array('/site/onthego')),
				array('label'=>'add store', 'url'=>array('/store/create'),'visible'=>!Yii::app()->user->isGuest),
				//array('label'=>'Login', 'url'=>array('/site/login'), 'visible'=>Yii::app()->user->isGuest),
				//array('label'=>'Logout ('.Yii::app()->user->name.')', 'url'=>array('/site/logout'), 'visible'=>!Yii::app()->user->isGuest)
			),
		)); 
		?>
	</div><!-- mainmenu -->
	<br class="clearfloat" />
	<?php /* if(isset($this->breadcrumbs)):?>
		<?php $this->widget('zii.widgets.CBreadcrumbs', array(
			'links'=>$this->breadcrumbs,
		)); ?><!-- breadcrumbs -->
	<?php endif */?>

	<?php echo $content; ?>

	<div class="clear"></div>

<br class="clearfloat" />
    <!-- Begin Footer -->
    <!---------------------------------------------------------------------------->
    <div id="footer">
    <div class="footerMenu">
        <ul>     
            <li>Copyright &copy; 2010 CanadianPassportPhotos.ca. All rights reserved.</li>
           <!-- <li><a href="site_privacy.html">Privacy</a></li>-->
            <li><span style="text-align: right"><a href="site_contact.html">Contact us</a></span></li>
        </ul>    
    </div>
    <!-- end #footer --></div>
	
<!----------------------------------------------------------------->
</div>

</div><!-- page -->

</body>
</html>